name: consumer-pipeline

on:
  workflow_dispatch:
  pull_request:

env:
  PACT_BROKER_BASE_URL: https://danrusu.pactflow.io
  PACT_PROVIDER: pact-provider-poc
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  API_BASE_URL: http://localhost:4000
  GIT_COMMIT: ${{ github.sha }}
  GIT_REF: ${{ github.ref }}

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    name: Unit tests (fake)
    steps:
      - run: echo "Successfull unit tests"

  contract-tests:
    runs-on: ubuntu-latest
    name: Contract tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run contract tests
        run: npm run test:pact

      - name: Get short sha
        run: |
          echo ::set-env name=SHORT_SHA::$(git rev-parse --short head)

      - name: Publish pacts between pactflow-example-consumer and ${{ env.PACT_PROVIDER }}
        run: |
          docker run \
            -w /opt/pact \
            -v ${PWD}/pact/pacts:/opt/pact \
            -e PACT_BROKER_BASE_URL=${{ env.PACT_BROKER_BASE_URL }}
            -e PACT_BROKER_TOKEN=${{ env.PACT_BROKER_TOKEN }}
            pactfoundation/pact-cli:latest publish . \
            --consumer-app-version ${{ env.SHORT_SHA }} \
            --branch ${{env.GIT_REF }} \

  deploy:
    needs:
      - unit-tests
      - contract-tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy to PREPROD"
